name:                may-haskell
version:             0.1.0.0
github:              "githubuser/may-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/may-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- serverless-haskell
- aeson
- lens
- graphql >= 0.9.0.0
- text
- unordered-containers
- hspec
- amazonka-dynamodb
- mtl
- jwt
- amazonka
- amazonka-core
- exceptions


library:
  source-dirs: src
ghc-options:
  - -Wall

executables:
  may-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - may-haskell

tests:
  may-haskell-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - may-haskell
